#!/usr/bin/env python3
"""
Security_Code version 1
Python 3.7.3
"""

import datetime
import fileinput
import random
import string


def expiration():
    """
    Set an expiration date with a two letter
    security code that changes to indicate expiration.
    """
    date = datetime.datetime.now()
    expires = (f'{date.year}-0{date.month}-0{date.day + 1}')
    letters = string.ascii_uppercase
    list_date = list(str(date))
    del list_date[10:26]
    new_date = ''.join(list_date)

    with open('transfer.txt', 'r+') as file:
        current_data = file.read()

        if new_date in current_data:
            current_data = current_data.replace(new_date, expires)

            with open('transfer.txt', 'w') as file:
                file.write(current_data)

        else:
            if new_date in expires:
                code_1 = random.choice(letters)
                code_2 = random.choice(letters)
                day_code = (f'{code_1}{code_2}')

                with open('transfer.txt', 'w') as file:
                    file.write(f'Expires: {expires}\n{day_code}')

            else:
                with open('transfer.txt', 'r') as file:
                    current_data = file.readlines()

                    if current_data == ['\n'] or []:
                        with open('transfer.txt', 'w') as file:
                            file.write(f'Expires: {new_date}')
                    else:
                        pass


if __name__ == '__main__':
    expiration()
